-- Rollback-only Group 7c interval checks; no invitations or fixtures remain.
begin;
do $$
declare
  center uuid := '10000000-0000-4000-a000-000000000001';
  owner_id uuid := '00000000-0000-4000-a000-000000000001';
  person uuid:=gen_random_uuid(); member uuid; room uuid; other_room uuid; shift_id uuid; cover uuid;
  day date:=current_date+30; a timestamptz; b timestamptz; x record;
begin
  update public.daycares set timezone='America/Toronto',opens_at='06:30',closes_at='19:30' where id=center;
  delete from public.center_closures where daycare_id=center;
  insert into public.classrooms(daycare_id,name,capacity,ratio_children_per_educator) values(center,'Rollback availability',12,4) returning id into room;
  insert into public.classrooms(daycare_id,name,capacity,ratio_children_per_educator) values(center,'Rollback other room',12,4) returning id into other_room;
  insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
    values(person,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','coverage-test-'||person||'@dailylog.invalid','',now(),'{"provider":"email","providers":["email"]}','{"full_name":"Rollback coverage candidate"}',now(),now());
  update public.profiles set role='educator',daycare_id=center,classroom_id=null where id=person;
  insert into public.staff_members(daycare_id,profile_id,status) values(center,person,'active') returning id into member;
  perform set_config('request.jwt.claims',json_build_object('sub',owner_id,'role','authenticated')::text,true);
  set local role authenticated;
  select * into x from public.get_coverage_candidates(room,day,'12:00','14:00') where profile_id=person;
  if not x.available or not x.needs_confirmation then raise exception 'FAIL: missing shift was advertised as confirmed'; end if;
  begin perform public.assign_planned_room_coverage(person,room,day,'12:00','14:00'); raise exception 'FAIL: unscheduled coverage skipped confirmation';
  exception when others then if sqlerrm like 'FAIL:%' then raise; end if; end;
  cover:=public.assign_planned_room_coverage(person,room,day,'12:00','14:00',true);
  if not exists(select 1 from public.room_coverage_assignments where id=cover and starts_at=(day+time '12:00') at time zone 'America/Toronto') then raise exception 'FAIL: wrong center timezone'; end if;
  select * into x from public.get_coverage_candidates(room,day,'13:00','15:00') where profile_id=person;
  if x.available then raise exception 'FAIL: overlapping coverage offered'; end if;
  select * into x from public.get_coverage_candidates(room,day,'14:00','15:00') where profile_id=person;
  if not x.available then raise exception 'FAIL: adjacent coverage blocked'; end if;
  update public.room_coverage_assignments set status='cancelled' where id=cover;
  reset role;
  insert into public.staff_shifts(daycare_id,staff_member_id,classroom_id,starts_at,ends_at,status,unpaid_break_minutes)
    values(center,member,null,(day+time '07:00') at time zone 'America/Toronto',(day+time '18:00') at time zone 'America/Toronto','published',30) returning id into shift_id;
  set local role authenticated;
  select * into x from public.get_coverage_candidates(room,day,'12:00','14:00') where profile_id=person;
  if not x.needs_confirmation then raise exception 'FAIL: untimed break treated as free'; end if;
  perform public.set_planned_shift_break(shift_id,'12:00','12:30');
  select * into x from public.get_coverage_candidates(room,day,'12:00','14:00') where profile_id=person;
  if x.available or x.reason not like '%break%' then raise exception 'FAIL: planned break ignored'; end if;
  select * into x from public.get_coverage_candidates(room,day,'12:30','14:00') where profile_id=person;
  if not x.available or x.needs_confirmation then raise exception 'FAIL: available post-break interval not offered'; end if;
  cover:=public.assign_planned_room_coverage(person,room,day,'12:30','14:00');
  begin perform public.set_planned_shift_break(shift_id,'13:00','13:30'); raise exception 'FAIL: break overwrote coverage';
  exception when others then if sqlerrm like 'FAIL:%' then raise; end if; end;
  begin perform public.set_planned_shift_break(shift_id,'06:00','06:30'); raise exception 'FAIL: out-of-shift break accepted';
  exception when check_violation then null; end;
  update public.room_coverage_assignments set status='cancelled' where id=cover;
  reset role;
  update public.staff_shifts set classroom_id=other_room where id=shift_id;
  insert into public.children(daycare_id,classroom_id,first_name,last_name,enrolled_on)
    values(center,other_room,'Rollback unknown','Demand',current_date);
  set local role authenticated;
  select * into x from public.get_coverage_candidates(room,day,'14:00','15:00') where profile_id=person;
  if x.available or x.reason not like 'Source-room forecast cannot safely lend%' then raise exception 'FAIL: conflicting published shift with unknown demand ignored'; end if;
  reset role;
  update public.staff_shifts set classroom_id=null where id=shift_id;
  insert into public.staff_time_off_requests(daycare_id,staff_member_id,starts_on,ends_on,kind,status) values(center,member,day,day,'vacation','approved');
  set local role authenticated;
  select * into x from public.get_coverage_candidates(room,day,'14:00','15:00') where profile_id=person;
  if x.available or x.reason not like 'Approved%' then raise exception 'FAIL: approved leave ignored'; end if;
  begin insert into public.room_coverage_assignments(daycare_id,classroom_id,staff_member_id,starts_at,ends_at) values(center,room,member,(day+time '14:00') at time zone 'America/Toronto',(day+time '15:00') at time zone 'America/Toronto'); raise exception 'FAIL: direct insert bypassed leave';
  exception when check_violation then null; end;
  reset role;
  delete from public.staff_time_off_requests where staff_member_id=member;
  update public.profiles set classroom_id=other_room where id=person;
  set local role authenticated;
  select * into x from public.get_coverage_candidates(room,day,'14:00','15:00') where profile_id=person;
  if x.available or x.reason not like 'Source-room forecast cannot safely lend%' then raise exception 'FAIL: home-room educator was treated as spare'; end if;
  reset role;
  update public.profiles set classroom_id=null where id=person;
  update public.staff_members set background_check_required=true where id=member;
  set local role authenticated;
  select * into x from public.get_coverage_candidates(room,day,'14:00','15:00') where profile_id=person;
  if x.available then raise exception 'FAIL: pending clearance offered'; end if;
  reset role;
  update public.staff_members set background_check_required=false where id=member;
  set local role authenticated;
  begin perform public.assign_planned_room_coverage(person,room,day,'06:00','07:00',true); raise exception 'FAIL: outside center hours accepted';
  exception when others then if sqlerrm like 'FAIL:%' then raise; end if; end;
  reset role;
  insert into public.center_closures(daycare_id,starts_on,ends_on,reason) values(center,day,day,'Rollback closure');
  set local role authenticated;
  begin perform public.assign_planned_room_coverage(person,room,day,'14:00','15:00',true); raise exception 'FAIL: closure ignored';
  exception when others then if sqlerrm like 'FAIL:%' then raise; end if; end;
  reset role;
  perform set_config('request.jwt.claims',json_build_object('sub',person,'role','authenticated')::text,true);
  set local role authenticated;
  begin perform public.set_planned_shift_break(shift_id,'15:00','15:30'); raise exception 'FAIL: educator edited break plan';
  exception when others then if sqlerrm like 'FAIL:%' then raise; end if; end;
end $$;
rollback;
select 'PASS: interval conflicts, leave, clearance, timed breaks, confirmation, center hours/closure and permissions; rolled back' as result;
