import { getMyDaycare, getMyProfile, listAttendanceDay } from "@dailylog/db/queries";
import { isAdminRole } from "@dailylog/shared";
import { redirect } from "next/navigation";
import { getServerSupabase } from "@/lib/supabase/server";

// Daily sign-in sheet 8e — print-friendly export, opened in a new tab from 8a.
export default async function AttendanceSheetPage({
  searchParams,
}: {
  searchParams: Promise<{ date?: string }>;
}) {
  const params = await searchParams;
  const today = new Date().toISOString().slice(0, 10);
  const date = /^\d{4}-\d{2}-\d{2}$/.test(params.date ?? "") ? params.date! : today;

  const supabase = await getServerSupabase();
  const profile = await getMyProfile(supabase);
  if (!isAdminRole(profile?.role)) redirect("/use-the-app");

  const [daycare, rows] = await Promise.all([
    getMyDaycare(supabase),
    listAttendanceDay(supabase, date),
  ]);

  const label = new Date(`${date}T12:00`).toLocaleDateString("en-CA", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const timeOf = (timestamp: string | null) =>
    timestamp
      ? new Date(timestamp).toLocaleTimeString("en-CA", { hour: "numeric", minute: "2-digit" })
      : "";

  return (
    <main className="mx-auto max-w-3xl bg-white p-10 font-sans text-ink print:p-0">
      <div className="mb-6 flex items-baseline justify-between border-b-2 border-ink pb-3">
        <span>
          <span className="block text-[18px] font-extrabold">{daycare?.name}</span>
          <span className="block text-[12px] text-muted">Daily sign-in sheet · {label}</span>
        </span>
        <button
          type="button"
          className="rounded-btn border-[1.5px] border-[#D6E1F0] px-4 py-2 text-[13px] font-bold text-primary print:hidden"
        >
          Print with ⌘P
        </button>
      </div>

      <table className="w-full border-collapse text-[13px]">
        <thead>
          <tr className="border-b-2 border-ink text-left font-mono text-[10.5px] tracking-[.07em] text-muted">
            <th className="py-2 pr-3 font-bold">CHILD</th>
            <th className="py-2 pr-3 font-bold">ROOM</th>
            <th className="py-2 pr-3 font-bold">IN</th>
            <th className="py-2 pr-3 font-bold">OUT</th>
            <th className="py-2 pr-3 font-bold">DROPPED OFF / PICKED UP</th>
            <th className="py-2 font-bold">STATUS</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => {
            const att = row.attendance[0];
            return (
              <tr key={row.id} className="border-b border-[#E4ECF6]">
                <td className="py-2 pr-3 font-bold">
                  {row.first_name} {row.last_name}
                </td>
                <td className="py-2 pr-3">{row.classroom?.name ?? "—"}</td>
                <td className="py-2 pr-3">{timeOf(att?.checked_in_at ?? null)}</td>
                <td className="py-2 pr-3">{timeOf(att?.checked_out_at ?? null)}</td>
                <td className="py-2 pr-3 text-[12px]">
                  {[att?.dropped_off_by, att?.picked_up_by].filter(Boolean).join(" / ") || "—"}
                </td>
                <td className="py-2 text-[12px]">
                  {att?.status === "absent" || att?.status === "excused"
                    ? `${att.status}${att.absence_reason ? ` · ${att.absence_reason}` : ""}`
                    : att?.checked_in_at
                      ? "present"
                      : "—"}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <p className="mt-6 text-[11px] text-faint">
        Generated by DailyLog · every entry is time-stamped and signed in the audit
        trail · {rows.length} children listed
      </p>
    </main>
  );
}
