import {
  getMyDaycare,
  getMyProfile,
  listAttendanceCorrections,
  listAttendanceDay,
} from "@dailylog/db/queries";
import { isAdminRole } from "@dailylog/shared";
import { redirect } from "next/navigation";
import { getServerSupabase } from "@/lib/supabase/server";
import { PrintButton } from "@/components/attendance/print-button";

// Daily sign-in sheet 8e — print-friendly export, opened in a new tab from 8a.
export default async function AttendanceSheetPage({
  searchParams,
}: {
  searchParams: Promise<{ date?: string; room?: string }>;
}) {
  const params = await searchParams;
  const today = new Date().toISOString().slice(0, 10);
  const date = /^\d{4}-\d{2}-\d{2}$/.test(params.date ?? "") ? params.date! : today;

  const supabase = await getServerSupabase();
  const profile = await getMyProfile(supabase);
  if (!isAdminRole(profile?.role)) redirect("/use-the-app");

  const [daycare, allRows] = await Promise.all([
    getMyDaycare(supabase),
    listAttendanceDay(supabase, date),
  ]);
  const rows = params.room
    ? allRows.filter((row) => row.classroom?.id === params.room)
    : allRows;
  const corrections = await listAttendanceCorrections(
    supabase,
    rows.flatMap((row) => row.attendance.map((record) => record.id)),
  );

  const label = new Date(`${date}T12:00`).toLocaleDateString("en-CA", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const timeOf = (timestamp: string | null) =>
    timestamp
      ? new Date(timestamp).toLocaleTimeString("en-CA", {
          hour: "numeric",
          minute: "2-digit",
          timeZone: daycare?.timezone ?? "America/Toronto",
        })
      : "";

  return (
    <main className="mx-auto max-w-3xl bg-white p-10 font-sans text-ink print:p-0">
      <div className="mb-6 flex items-baseline justify-between border-b-2 border-ink pb-3">
        <span>
          <span className="block text-[18px] font-extrabold">{daycare?.name}</span>
          <span className="block text-[12px] text-muted">Daily sign-in sheet · {label}</span>
        </span>
        <PrintButton />
      </div>

      <table className="w-full border-collapse text-[13px]">
        <thead>
          <tr className="border-b-2 border-ink text-left font-mono text-[10.5px] tracking-[.07em] text-muted">
            <th className="py-2 pr-3 font-bold">CHILD</th>
            <th className="py-2 pr-3 font-bold">ROOM</th>
            <th className="py-2 pr-3 font-bold">IN</th>
            <th className="py-2 pr-3 font-bold">OUT</th>
            <th className="py-2 pr-3 font-bold">BY</th>
            <th className="py-2 pr-3 font-bold">BY</th>
            <th className="py-2 font-bold">STATUS</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => {
            const att = row.attendance[0];
            return (
              <tr key={row.id} className="border-b border-[#E4ECF6]">
                <td className="py-2 pr-3 font-bold">
                  {row.first_name} {row.last_name}
                </td>
                <td className="py-2 pr-3">{row.classroom?.name ?? "—"}</td>
                <td className="py-2 pr-3">{timeOf(att?.checked_in_at ?? null)}</td>
                <td className="py-2 pr-3">{timeOf(att?.checked_out_at ?? null)}</td>
                <td className="py-2 pr-3 text-[12px]">{att?.dropped_off_by || "—"}</td>
                <td className="py-2 pr-3 text-[12px]">{att?.picked_up_by || "—"}</td>
                <td className="py-2 text-[12px]">
                  {att?.status === "absent" || att?.status === "excused"
                    ? `${att.status}${att.absence_reason ? ` · ${att.absence_reason}` : ""}`
                    : att?.checked_in_at
                      ? "present"
                      : "—"}
                  {att && corrections.some((item) => item.attendance_id === att.id) ? " · corrected" : ""}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <p className="mt-6 text-[11px] text-faint">
        Generated by DailyLog · every entry is time-stamped and signed in the audit
        trail · {rows.length} children listed
      </p>
      {corrections.length > 0 && (
        <section className="mt-5 border-t border-[#D6E1F0] pt-4 text-[10.5px] text-muted">
          <h2 className="font-bold text-ink">Correction notes</h2>
          {corrections.map((correction) => {
            const row = rows.find((item) => item.attendance[0]?.id === correction.attendance_id);
            return (
              <p key={correction.id} className="mt-1">
                {row ? `${row.first_name} ${row.last_name}` : "Attendance record"} · {correction.reason}
                {correction.corrected_by_profile?.full_name
                  ? ` · edited by ${correction.corrected_by_profile.full_name}`
                  : ""}
              </p>
            );
          })}
        </section>
      )}
    </main>
  );
}
